### ISSUE TITLE
Initialize-KoanDirectory parameter and confirmation could be misleading.

### ISSUE THREAD

**Issue by BrandonLundt** [vexx32/PSKoans#15]
From issue #12 

> So either we need to change the ConfirmImpact of the function to High or we need to alter the call that the Get-Enlightenment function does with the -Reset switch to call the Initialize-KoanDirectory function with the -Confirm switch.

My opinion is,  Initialize-KoanDirectory is not an exported function, so the simplest option is to remove the -FirstImport parameter and set ConfirmImpact to High.

Could easily be convinced the other direction.

**Comment by vexx32** [comment]
Either route we go, I want the 'first run', so to speak, to execute without confirmation (because the test for whether the koan files are present is already run). So I guess that means... removing `-FirstRun` and just having the initial run be executed with `-Confirm:$false`, which amounts to much the same.

_Unless_ you think it would be better to have it be an additional setup step, which... I mean, wouldn't be bad, but I think it would be a little unnecessary.

**Comment by BrandonLundt** [comment]
Another item to consider as we work on issue #13 unit testing might get weird if every time we want to test it has to import the entire psm1. Not a huge deal, just thinking out loud.

**Comment by vexx32** [comment]
In what way? Importing the PSM1 shouldn't be a big deal. We can either break it out into functions (and combine it with a build script for releases) or just add some bits and pieces so that it doesn't create scores of koan files when we're just testing the main functions, etc., etc.

**Comment by vexx32** [comment]
Should be good to go for now. @BrandonLundt you may want to update #16 with the new code & syntax so you don't have to edit after merging. 😄
